# Generated by Django 6.0 on 2025-12-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_num',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emai_address',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
